### ISSUE TITLE
Do you have a plan to release for Noetic?

### ISSUE THREAD

**Issue by OTL** [peci1/tf2_server#1]
I tried to build/test on noetic, and it succeeded.
We are very happy if you could release for noetic!

**Comment by peci1** [comment]
Hi. I see you first reported a build failure and then edited the issue. Has the build failure resolution been unrelated to this package?

**Comment by OTL** [comment]
Sorry, this issue is completely mistaken (Not only build failure).
I thought that we are using your package, but actually not...
